const data = {
  data: [
    {
      sku: '190198790408',
      make: 'Apple',
      model: 'iPhone XS',
      pricing: { price: 1379, msrp: 1379 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 30,
        savingAmount: 659,
        payoffPeriodMonths: 24,
      },
      plan: { price: 40, sku: 'Freedom 2GB' },
      isInStock: true,
    },
    {
      sku: '190198776419',
      make: 'Motorola',
      model: 'One Action',
      pricing: { price: 799, msrp: 799 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 30,
        savingAmount: 79,
        payoffPeriodMonths: 24,
      },
      plan: { price: 35, sku: 'Freedom 1GB' },
      isInStock: true,
    },
    {
      sku: '190199220645',
      make: 'Apple',
      model: 'iPhone 11',
      pricing: { price: 979, msrp: 979 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 20,
        savingAmount: 499,
        payoffPeriodMonths: 24,
      },
      plan: { price: 65, sku: 'Promo Big Gig Unlimited + Talk 11GB' },
      isInStock: false,
    },
    {
      sku: '887276270173',
      make: 'LG',
      model: 'Q Stylo+',
      pricing: { price: 1300, msrp: 1300 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 50,
        savingAmount: 100,
        payoffPeriodMonths: 24,
      },
      plan: { price: 25, sku: 'Freedom 500MB' },
      isInStock: true,
    },
    {
      sku: '652810830737',
      make: 'LG',
      model: 'G7 ThinQ',
      pricing: { price: 536, msrp: 536 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 0,
        savingAmount: 536,
        payoffPeriodMonths: 24,
      },
      plan: { price: 50, sku: 'Big Gig Unlimited 10GB' },
      isInStock: false,
    },
    {
      sku: '842776114952',
      make: 'Google',
      model: 'Pixel 3 XL',
      pricing: { price: 999, msrp: 999 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 25,
        savingAmount: 399,
        payoffPeriodMonths: 24,
      },
      plan: { price: 60, sku: 'Big Gig Unlimited + Talk 10GB' },
      isInStock: false,
    },
    {
      sku: '887276331195',
      make: 'Samsung',
      model: 'Galaxy S10+',
      pricing: { price: 1750, msrp: 1750 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 55,
        savingAmount: 430,
        payoffPeriodMonths: 24,
      },
      plan: { price: 50, sku: 'Freedom 5GB' },
      isInStock: false,
    },
    {
      sku: '887276322575',
      make: 'Samsung',
      model: 'Galaxy S10e',
      pricing: { price: 980, msrp: 980 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 30,
        savingAmount: 260,
        payoffPeriodMonths: 24,
      },
      plan: { price: 55, sku: 'Promo Freedom 6GB' },
      isInStock: false,
    },
    {
      sku: '887276299440',
      make: 'Samsung',
      model: 'Galaxy Tab A 8 LTE ',
      pricing: { price: 279, msrp: 279 },
      smartTab: {
        outrightPayment: 0,
        monthlyPayment: 0,
        savingAmount: 279,
        payoffPeriodMonths: 0,
      },
      plan: { price: 15, sku: 'Promo Tablet 15' },
      isInStock: false,
    },
  ],
  pagination: null,
};

export default data;
